/*
CREATED		06/08/2013
MODIFIED		13/09/2020
PROJECT		
MODEL			
COMPANY		
AUTHOR		
VERSION		
DATABASE		MS SQL 2005 
*/


CREATE TABLE [PARTICIPANTE]
(
	[ID_PARTICIPANTE] BIGINT IDENTITY NOT NULL,
	[NOME] VARCHAR(100) NOT NULL,
	[CPF] VARCHAR(11) NOT NULL,
	[EMAIL] VARCHAR(100) NULL,
PRIMARY KEY ([ID_PARTICIPANTE])
) 
GO

CREATE TABLE [EVENTO]
(
	[ID_EVENTO] BIGINT IDENTITY NOT NULL,
	[ID_UNIDADE] BIGINT NOT NULL,
	[NOME] VARCHAR(100) NOT NULL,
	[ARQUIVO_CERTIFICADO] VARCHAR(100) NOT NULL,
	[X] INTEGER NOT NULL,
	[Y] INTEGER NOT NULL,
	[DATA_LIBERACAO_DOCUMENTO] DATETIME NOT NULL,
PRIMARY KEY ([ID_EVENTO])
) 
GO

CREATE TABLE [HISTORICO]
(
	[ID_HISTORICO] BIGINT IDENTITY NOT NULL,
	[ID_EVENTO_PARTICIPANTE] BIGINT NOT NULL,
	[DATA_HORA] DATETIME NOT NULL,
PRIMARY KEY ([ID_HISTORICO])
) 
GO

CREATE TABLE [USUARIO]
(
	[ID_USUARIO] BIGINT IDENTITY NOT NULL,
	[ID_UNIDADE] BIGINT NOT NULL,
	[NOME] VARCHAR(100) NOT NULL,
	[LOGIN] VARCHAR(50) NOT NULL,
	[SENHA] VARCHAR(50) NOT NULL,
	[E_MAIL] VARCHAR(100) NOT NULL,
PRIMARY KEY ([ID_USUARIO])
) 
GO

CREATE TABLE [UNIDADE]
(
	[ID_UNIDADE] BIGINT IDENTITY NOT NULL,
	[DESCRICAO] VARCHAR(100) NOT NULL,
	[ATIVO] SMALLINT NOT NULL,
PRIMARY KEY ([ID_UNIDADE])
) 
GO

CREATE TABLE [EVENTO_PARTICIPANTE]
(
	[ID_EVENTO_PARTICIPANTE] BIGINT IDENTITY NOT NULL,
	[ID_PARTICIPANTE] BIGINT NOT NULL,
	[ID_EVENTO] BIGINT NOT NULL,
PRIMARY KEY ([ID_EVENTO_PARTICIPANTE])
) 
GO


CREATE UNIQUE INDEX [IX_PARTICIPANTE_CPF] ON [PARTICIPANTE] ([CPF] ) 
GO
CREATE UNIQUE INDEX [IX_EVENTO] ON [EVENTO] ([ID_UNIDADE] ,[NOME] ) 
GO
CREATE UNIQUE INDEX [IX_EVENTO2] ON [EVENTO] ([ARQUIVO_CERTIFICADO] ) 
GO
CREATE UNIQUE INDEX [IX_USUARIO_LOGIN] ON [USUARIO] ([LOGIN] ) 
GO
CREATE INDEX [IX_UNIDADE] ON [UNIDADE] ([DESCRICAO] ) 
GO
CREATE UNIQUE INDEX [IX_EVENTO_PARTICIPANTE] ON [EVENTO_PARTICIPANTE] ([ID_PARTICIPANTE] ,[ID_EVENTO] ) 
GO


ALTER TABLE [EVENTO_PARTICIPANTE] ADD  FOREIGN KEY([ID_PARTICIPANTE]) REFERENCES [PARTICIPANTE] ([ID_PARTICIPANTE])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [EVENTO_PARTICIPANTE] ADD  FOREIGN KEY([ID_EVENTO]) REFERENCES [EVENTO] ([ID_EVENTO])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [USUARIO] ADD  FOREIGN KEY([ID_UNIDADE]) REFERENCES [UNIDADE] ([ID_UNIDADE])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [EVENTO] ADD  FOREIGN KEY([ID_UNIDADE]) REFERENCES [UNIDADE] ([ID_UNIDADE])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [HISTORICO] ADD  FOREIGN KEY([ID_EVENTO_PARTICIPANTE]) REFERENCES [EVENTO_PARTICIPANTE] ([ID_EVENTO_PARTICIPANTE])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO


SET QUOTED_IDENTIFIER ON
GO


SET QUOTED_IDENTIFIER OFF
GO


